version: '3.8'

services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: kryptotracker
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin123!
    volumes:
      - ./backend/db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - '8080:80'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: kryptotracker
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

#  frontend:
#    build:
#      context: ./frontend/
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./frontend/react_webapp:/app/frontend
#      - /app/frontend/node_modules # verhindert, dass lokales node_modules das im container überschreibt
#    depends_on:
#      - backend

volumes:
  db_data: