version: '3'

services:
  db:
    image: mysql:8.1.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./backend/db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - db

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - '8000:8000'
#    volumes:
#      - ./backend/django_backend:/app/backend/django_backend
#    restart: on-failure
#    depends_on:
#      - db

volumes:
  db_data: