# Generated by Django 4.2.8 on 2024-01-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kryptotracker", "0004_assetinfo_assetowned_historicalassetinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetinfo",
            name="acronym",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="assetinfo",
            name="current_price",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalassetinfo",
            name="acronym",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalassetinfo",
            name="current_price",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
