# Generated by Django 4.2.8 on 2024-01-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kryptotracker", "0005_alter_assetinfo_acronym_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetinfo",
            name="acronym",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="assetinfo",
            name="api_id_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="assetinfo",
            name="fullname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalassetinfo",
            name="acronym",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalassetinfo",
            name="api_id_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalassetinfo",
            name="fullname",
            field=models.CharField(max_length=255),
        ),
    ]
