# Generated by Django 4.2.8 on 2024-01-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kryptotracker", "0007_alter_transaction_tx_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetinfo",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalassetinfo",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
